// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"BONCOS_HUD","status":true,"description":"HUD sederhana menampilkan Utang dan Saldo di layar map.","parameters":{"varUtang":"2","varSaldo":"1","varObjektif":"10","varHari":"11","varGiliran":"12","varEnergi":"13","varNilai":"14","switchAktif":"2"}},
{"name":"BONCOS_MapLabels","status":true,"description":"Menampilkan teks nama gedung di atas tile tertentu di map (ikut scroll kamera).","parameters":{"labels":"[\"{\\\"mapId\\\":\\\"2\\\",\\\"x\\\":\\\"25\\\",\\\"y\\\":\\\"29\\\",\\\"text\\\":\\\"Universitas Brawicos\\\"}\",\"{\\\"mapId\\\":\\\"2\\\",\\\"x\\\":\\\"29\\\",\\\"y\\\":\\\"16\\\",\\\"text\\\":\\\"Apartemen\\\"}\",\"{\\\"mapId\\\":\\\"2\\\",\\\"x\\\":\\\"7\\\",\\\"y\\\":\\\"33\\\",\\\"text\\\":\\\"Supermarket (Kerja)\\\"}\",\"{\\\"mapId\\\":\\\"2\\\",\\\"x\\\":\\\"10\\\",\\\"y\\\":\\\"26\\\",\\\"text\\\":\\\"Warung makan\\\"}\"]"}},
{"name":"BONCOS_HUD (1)","status":false,"description":"HUD sederhana menampilkan Utang dan Saldo di layar map.","parameters":{"varUtang":"2","varSaldo":"1","varObjektif":"5","varHari":"11","varGiliran":"12","varEnergi":"13","varNilai":"14","switchAktif":"2"}},
{"name":"BONCOS_HUD (2)","status":false,"description":"HUD sederhana menampilkan Utang dan Saldo di layar map.","parameters":{"varUtang":"2","varSaldo":"1","varObjektif":"10","varHari":"11","varGiliran":"12","varEnergi":"13","varNilai":"14","switchAktif":"2"}},
{"name":"BONCOS_HUD (3)","status":false,"description":"HUD sederhana menampilkan Utang dan Saldo di layar map.","parameters":{"varUtang":"2","varSaldo":"1","varObjektif":"10","varHari":"11","varGiliran":"12","varEnergi":"13","varNilai":"14","switchAktif":"2"}},
{"name":"BONCOS_HUD (4)","status":false,"description":"HUD BONCOS: Utang, Saldo, Objektif, Hari, dan bar Energi/Nilai — dicari berdasarkan NAMA variable.","parameters":{"nameUtang":"Utang","nameSaldo":"Saldo","nameObjektif":"Objektif","nameHari":"HariKe","nameGiliran":"GiliranKe","nameEnergi":"Energi","nameNilai":"Nilai","nameSwitchPenampil":"Level1Selesai"}}
];
